import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "./provider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My TodoList",
  description: "Generated by create next app"
};

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <div>
            <Navbar />
            {children}
          </div>
        </QueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
