import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/report">Report</Link>
            <Link href="/todolist/csr">TodoList(CSR)</Link>
            <Link href="/todolist/ssr">TodoList(SSR)</Link>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
